version: '3.3'
services:
  web:
    build: ./
    command: gunicorn geekshop.wsgi
    volumes:
      - ./:/usr/src/geekshop/
    ports:
      - '8000:8000'
      - '80:80'
    env_file:
      - ./geekshop/.env
